---
apiVersion: eks.aws.crossplane.io/v1beta1
kind: Cluster
metadata:
  name: steven953
  labels:
    example: "true"
spec:
  forProvider:
    region: us-east-1
    resourcesVpcConfig:
      endpointPublicAccess: false
      endpointPrivateAccess: true
      subnetIds:
        - subnet-6e952535
        - subnet-25f94608
    roleArn: arn:aws:iam::484346401365:role/eks-cluster-role
    tags:
      - key: Name
        value: steven953
      - key: Owner
        value: "Steven Barnes"
      - key: Team
        value: "Venue Product Team"
    version: "1.19"
