---
apiVersion: eks.aws.crossplane.io/v1beta1
kind: Cluster
metadata:
  name: steven953
  labels:
    example: "true"
spec:
  forProvider:
    region: us-east-1
    resourcesVpcConfig:
      endpointPublicAccess: false
      endpointPrivateAccess: true
      subnetIds:
        - subnet-6e952535
        - subnet-25f94608
    roleArn: arn:aws:iam::484346401365:role/eks-cluster-role
    tags:
      Name: steven953
      Owner: "Steven Barnes"
      Team: "Venue Product Team"
    version: "1.19"

---

apiVersion: eks.aws.crossplane.io/v1alpha1
kind: NodeGroup
metadata:
  name: steven953-ng-1
  labels:
    example: "true"
spec:
  forProvider:
    region: us-east-1
    nodeRole: arn:aws:iam::484346401365:role/preprod-eks-worker-nodes-NodeInstanceRole-ERYWTH7QFDV2
    clusterNameRef:
      name: steven953
    tags:
      Name: steven953-ng-1
      Owner: "Steven Barnes"
      Team: "Venue Product Team"